CREATE TABLE author (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1000),
  nick_name  VARCHAR(30),
  birth_date DATE         NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name  VARCHAR(255) NOT NULL,
  version    BIGINT       NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE book (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1000),
  genre      VARCHAR(255),
  title      VARCHAR(50) NOT NULL,
  version    BIGINT      NOT NULL,
  library_id BIGINT,
  book_year  INTEGER     NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE book_author (
  book_id   BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  PRIMARY KEY (book_id, author_id)
);

CREATE TABLE book_review (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1000),
  content CLOB(255) NOT NULL,
  book_fk BIGINT    NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE library (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1000),
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE book
ADD CONSTRAINT FK_book_library_id
FOREIGN KEY (library_id)
REFERENCES library;

ALTER TABLE book_author
ADD CONSTRAINT FK_book_author_author_id
FOREIGN KEY (author_id)
REFERENCES author;

ALTER TABLE book_author
ADD CONSTRAINT FK_book_author_book_id
FOREIGN KEY (book_id)
REFERENCES book;

ALTER TABLE book_review
ADD CONSTRAINT FK_book_review_book_fk
FOREIGN KEY (book_fk)
REFERENCES book;
